---
- apt_key: keyserver=keyserver.ubuntu.com id=ACCAF35C state=present
  become: yes
  become_method: sudo

- apt_repository: repo='deb http://apt.insynchq.com/ubuntu {{ ansible_distribution_release }} non-free contrib' state=present
  become: yes
  become_method: sudo

- apt: name=insync state=latest update_cache=yes
  become: yes
  become_method: sudo

