---
- name: Add repositories
  apt_repository:
   repo: '{{ ppa }}'
  loop:
   - 'ppa:embrosyn/cinnamon'
   # - 'ppa:nilarimogard/webupd8'
  loop_control:
    loop_var: ppa

- apt:
    name:
      - nemo
      - nemo-audio-tab
      - nemo-compare
      - nemo-data
      # - nemo-dropbox
      - nemo-emblems
      - nemo-fileroller
      - nemo-gtkhash
      - nemo-image-converter
      - nemo-media-columns
      - nemo-pastebin
      - nemo-preview
      - nemo-seahorse
      - nemo-share
      - unoconv
      - gnumeric
      - unrar
      - zip
      - meld
      - libxreaderdocument3
      - libxreaderview3
  become: yes

# disable Nautilus from handling the desktop icons
# and set Nemo as the default file manager
# - name: Set nemo as default
  # command: "{{ item }}"
  # with_items:
  # - "gsettings set org.gnome.desktop.background show-desktop-icons false"
  # - "xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search"

# revert changes
# - name: Set nautilus as default
  # shell: {{ item }}
  # with_items:
  # - "gsettings set org.gnome.desktop.background show-desktop-icons true"
  # - "xdg-mime default nautilus.desktop inode/directory application/x-gnome-saved-search"


