---
- name: add paa firefox-next
  apt_repository:
    repo: ppa:mozillateam/firefox-next
    state: present
  become: yes


- name: install firefox
  package:
    name: firefox
    state: latest
  become: yes
