---
#- name: Add repositories flux gui
#  apt_repository: repo: ppa:nathan-renniewaldock/ppa
#  become: yes

- apt:
    name: '{{ item }}'
    state: latest
  become: yes
  with_items:
    #- fluxgui
  - redshift
  - redshift-gtk

