---
# Usage: ansible-playbook -K local.yml

- hosts: 127.0.0.1
  connection: local

  vars:
    - home: '{{ ansible_user_dir }}'
    - cloudstorage: '{{ home }}/Documents/OneDrive'
    - packaging_ubuntu_extras_repository: false
    - packaging_ubuntu_partner_repository: true
    - packaging_ubuntu_multiverse_repository: true


  roles:
    # - extra_repo     # extra repos
    # - ipv6           # disable ipv6 and extras
    # - grub2

    ## - dropbox
    # - encfs
    # - nemo
    # - bash
    # - zsh
    # - fzf
    # - vim
    # - tmux
    # - evolution
    # - zim
    # - java
    # - virtualbox
    # - vagrant
    # - pac
    # - ssh
    # - chrome
    # - vivaldi
    # - firefox
    # - networkmanager
    # - networktools
    # - ansible-tools
    # - apt-updates
    # - keepassxc
    # - fonts
    # - httpstat

    #### extra software
    ## - openxenmanager
    ## - tlp     # power manager
    ## - timeshift
    ## - shutter
    ## - rambox
    ## - beekeeperstudio
    ## - mysqlworkbench
    ## - mixed-content-scan
    ## - scripts     # tools and zabbix notification
    ## - beekeeperstudio
    - translate
    - filezilla
    - vscode
    - dbeaver
    - bingwall
    - ppa-manager
    - libreoffice
    - office
    - zeal
    - flameshot
    - testssl
    - powershell
    - masterpdf
    - bleachbit
    - vlc
    - geany
    - tools
    - apt-updates
    - gnome-tweaks
    - ulauncher
    - guake
    - peek        # gif recorder
    - postman
    - pycharm
    - skype
