---
- name: create dir
  file:
    path: '{{ home }}/apps/rambox'
    state: directory

- get_url:
    url: 'https://getrambox.herokuapp.com/download/x64?filetype=AppImage'
    url: 'https://github.com/ramboxapp/community-edition/releases/download/0.7.4/Rambox-0.7.4-linux-x86_64.AppImage'
    dest: '{{ home }}/apps/rambox'
