---
- apt:
    deb: https://releases.hashicorp.com/vagrant/2.2.5/vagrant_2.2.5_x86_64.deb
    state: present
  become: yes

- apt:
    name: nfs-kernel-server
    state: present
  become: yes

- name: install vagrant bash completion
  become: yes
  get_url:
    url: 'https://raw.github.com/kura/vagrant-bash-completion/master/etc/bash_completion.d/vagrant'
    dest: /etc/bash_completion.d/vagrant

