---
- apt: name=mysql-workbench state=present
  become: yes

- file: path={{ home }}/.mysql/workbench state=directory

- synchronize: src={{ home }}/Notebooks/carl/.mysql/workbench dest={{ home }}/.mysql/workbench
