---
# install libreoffice
- name: Add repositories libreoffice
  apt_repository:
    # repo: ppa:libreoffice/libreoffice-6-2
    repo: ppa:libreoffice/ppa
  become: yes

- apt:
    name:
      - libreoffice
    state: latest
  become: yes


# install freeoffice
- name: add softmaker repo key
  apt_key:
    data: "{{ lookup('file', 'softmaker.repository.gpg') }}"
    state: present
  become: yes

- name: add softmaker repo
  apt_repository:
    repo: 'deb http://shop.softmaker.com/repo/apt wheezy non-free'
    state: present
    update_cache: yes
  become: yes

- name: install softmaker
  apt:
    name: softmaker-freeoffice-2018
    state: latest
  become: yes

- name: install freeoffice license
  copy:
    dest: /etc/SoftMaker/offree2018.lic
    src: '{{ home }}/Notebooks/carl/etc/SoftMaker/offree2018.lic'


# install onlyoffice
- name: install onlyoffice snap
  snap:
    name: onlyoffice-desktopeditors
    state: present
  become: yes
