- name: Add repositories zeal
  apt_repository: repo=ppa:zeal-developers/ppa
  become: yes
  become_method: sudo

- apt: name={{ item }} state=latest
  become: yes
  become_method: sudo
  with_items:
  - zeal

