---
- name: keepassxc
  apt:
    name: keepassxc
    state: present
  become: yes

- name: copy keepass config
  synchronize:
    src: '{{ cloudstorage }}/carl/.config/keepassxc/'
    dest: '{{ home }}/.config/keepassxc/'
