---
- name: Add repositories themes
  apt_repository:
    repo: 'ppa:ravefinity-project/ppa'
  become: yes

- apt:
    name: '{{ item }}'
      - vibrancy-colors
      - vivacious-colors
    state: latest
  become: yes

