---
- apt:
    name:
      - htop
      - powertop
      - ncdu
    state: present
  become: yes

- synchronize:
    src: '{{ cloudstorage }}/carl/.config/htop'
    dest: '{{ home }}/.config/htop'

- name: disable apport
  service:
    name: apport
    state: stopped
    enabled: no
  become: yes
