---
# https://packagecloud.io/asbru-cm/asbru-cm/packages/ubuntu/bionic/libgnome2-vte-perl_0.11-1_amd64.deb/download.deb
- copy: src=libgnome2-vte-perl_0.11-1_amd64.deb dest=/tmp/libgnome2-vte-perl_0.11-1_amd64.deb

- name: install libgnome2-vte-perl
  apt: deb=/tmp/libgnome2-vte-perl_0.11-1_amd64.deb
  become: yes

### https://packagecloud.io/asbru-cm/asbru-cm
##- copy: src=asbru-cm_5.0.0-1_amd64.deb dest=/tmp/asbru-cm_5.0.0-1_amd64.deb
##
##- name: install asbru-cm
##  apt: deb=/tmp/asbru-cm_5.0.0-1_amd64.deb
##  become: yes
##

- name: Setup apt repository
  get_url:
    dest: "/etc/apt/sources.list.d/asbru-cm_asbru-cm.list"
    url: "https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/config_file.list?os={{ ansible_distribution }}&dist={{ ansible_distribution_release }}&source=script"
    owner: root
    group: root
    mode: 0644
  become: yes

- name: install asbru-cm gpg key
  apt_key:
    url: https://packagecloud.io/asbru-cm/asbru-cm/gpgkey
    state: present
  become: yes

- name: install asbru-cm
  apt:
    name: asbru-cm
    state: latest
  become: yes

- name: copy icon
  copy: src=server_white.svg dest=/usr/share/icons/hicolor/scalable/apps/server_white.svg
  become: yes

- name: change icon in desktop file
  lineinfile:
    path: /usr/share/applications/asbru-cm.desktop
    regexp: '^Icon=.*'
    line: 'Icon=/usr/share/icons/hicolor/scalable/apps/server_white.svg'
  become: yes

- stat: path={{ home }}/.config/pac
  register: pacdir

- pause: prompt="Start PAC and close it again."
  when: pacdir.stat.exists == false

- file: dest={{ home }}/.config/pac/{{ item }} state=absent
  with_items:
  - pac.dumper
  - pac.nfreeze
  - pac.yml
  - pac.yml.gui
  - pac.yml.tree
  - pac_notray.notified
  - pac_stats.nfreeze


- file: src={{ home }}/Notebooks/carl/.config/pac/{{ item }} dest={{ home }}/.config/pac/{{ item }} state=link
  with_items:
  - pac.dumper
  - pac.nfreeze
  - pac.yml
  - pac.yml.gui
  - pac.yml.tree
  - pac_notray.notified
  - pac_stats.nfreeze


