---
- name: Download pac-4.5.5.7-all.deb
  get_url:
    url="http://downloads.sourceforge.net/project/pacmanager/pac-4.0/pac-4.5.5.7-all.deb"
    dest="/tmp/pac.deb"

- name: Install pac-4.5.5.7-all.deb
  apt: deb="/tmp/pac.deb"
  become: yes
  become_method: sudo

- file: path=/home/carl/.config/pac state=directory

- file: src=/home/carl/Notebooks/carl/.config/pac/{{ item }} dest=/home/carl/.config/pac/{{ item }} state=link
  with_items:
  - pac.dumper
  - pac.nfreeze
  - pac.yml
  - pac.yml.gui
  - pac.yml.tree
  - pac_notray.notified
  - pac_stats.nfreeze
