---
# - name: Setup apt repository
#   apt_repository:
#     repo: "ppa:asbru-cm/{{ asbru_ppa }}"
#     state: present
#   become: yes

- name: install test script for 20.04
  shell: curl -s https://packagecloud.io/install/repositories/asbru-cm/loki/script.deb.sh | bash
  args:
    creates: /usr/bin/asbru-cm
  become: yes

- name: install asbru-cm latest version
  apt:
    name: asbru-cm
    state: latest
  become: yes


- name: copy icon
  copy:
    src: server_white.svg
    dest: /usr/share/icons/hicolor/scalable/apps/server_white.svg
  become: yes


- name: change icon in desktop file
  lineinfile:
    path: /usr/share/applications/asbru-cm.desktop
    regexp: '^Icon=.*'
    line: 'Icon=/usr/share/icons/hicolor/scalable/apps/server_white.svg'
  become: yes


- stat:
    path: '{{ home }}/.config/pac'
  register: pacdir


- pause:
    prompt: "Start PAC and close it again."
  when: not pacdir.stat.exists


- file:
    dest: '{{ home }}/.config/asbru/{{ item }}'
    state: absent
  with_items:
    - asbru.dumper
    - asbru.nfreeze
    - asbru.yml
    - asbru.yml.gui
    - asbru.yml.tree
    - asbru_notray.notified
    - asbru_stats.nfreeze


- file:
    src: '{{ home }}/Notebooks/carl/.config/pac/pac{{ item }}'
    dest: '{{ home }}/.config/asbru/asbru{{ item }}'
    state: link
  with_items:
    - .dumper
    - .nfreeze
    - .yml
    - .yml.gui
    - .yml.tree
    - _notray.notified
    - _stats.nfreeze

