---
# https://packagecloud.io/asbru-cm/asbru-cm/packages/ubuntu/bionic/libgnome2-vte-perl_0.11-1_amd64.deb/download.deb
- copy: src=libgnome2-vte-perl_0.11-1_amd64.deb dest=/tmp/libgnome2-vte-perl_0.11-1_amd64.deb

- name: install libgnome2-vte-perl
  apt:
    deb: /tmp/libgnome2-vte-perl_0.11-1_amd64.deb
  become: yes

- copy: src=asbru-cm_5.0.0-1_amd64.deb dest=/tmp/asbru-cm_5.0.0-1_amd64.deb

- apt: deb=/tmp/asbru-cm_5.0.0-1_amd64.deb
  become: yes



#- package: name={{ item }} state=present
#  become: yes
#  with_items:
#    - debian-archive-keyring
#    - gnupg
#    - apt-transport-https
#
#- apt_key: url="https://packagecloud.io/asbru-cm/asbru-cm/gpgkey"
#  become: yes
#
#- apt_repository:
#    repo: deb https://packagecloud.io/asbru-cm/snapshots/ubuntu/ bionic main
#    state: present
#  become: yes
#
#- package: name=asbru-cm state=installed
#  become: yes

#libvte-common libvte9
- pause: prompt="Start PAC and close it again."

- file: dest={{ home }}/.config/pac/{{ item }} state=absent
  with_items:
  - pac.dumper
  - pac.nfreeze
  - pac.yml
  - pac.yml.gui
  - pac.yml.tree
  - pac_notray.notified
  - pac_stats.nfreeze


- file: src={{ home }}/Notebooks/carl/.config/pac/{{ item }} dest={{ home }}/.config/pac/{{ item }} state=link
  with_items:
  - pac.dumper
  - pac.nfreeze
  - pac.yml
  - pac.yml.gui
  - pac.yml.tree
  - pac_notray.notified
  - pac_stats.nfreeze



##- name: Download pac-4.5.5.7-all.deb
##  get_url:
##    url="http://downloads.sourceforge.net/project/pacmanager/pac-4.0/pac-4.5.5.7-all.deb"
##    dest="/tmp/pac.deb"
##
##- name: Install pac-4.5.5.7-all.deb
##  apt: deb="/tmp/pac.deb"
##  become: yes
##
##- file: path={{ home }}/.config/pac state=directory

##- apt: name={{ item }} state=installed
##  with_items:
##    - libgtk2-appindicator-perl
##
##- copy: src=libgnome2-vte-perl_0.11-1_amd64.deb dest=/tmp/libvte.deb
##
##- apt: deb=/tmp/libvte.deb state=installed
##
##- command: find /opt/pac/ -name "Vte.so*" -exec rm {} +
##  become: yes



### create libgnome2-vte-perl_0.11-1_amd64.deb
#- apt: name={{ item }} state=installed
#  with_items:
#    - libglib2.0-dev
#    - libpango1.0-dev
#    - libvte-dev
#    - libvte-2.91-dev
#    - dh-make-perl
#    - libextutils-pkgconfig-perl
#    - libextutils-depends-perl
#
#- command: echo -e "\n\n\no\n" | dh-make-perl --cpan Gnome2::Vte --build
