---
# https://packagecloud.io/asbru-cm/asbru-cm/packages/ubuntu/bionic/libgnome2-vte-perl_0.11-1_amd64.deb/download.deb
- copy: src=libgnome2-vte-perl_0.11-1_amd64.deb dest=/tmp/libgnome2-vte-perl_0.11-1_amd64.deb

- name: install libgnome2-vte-perl
  apt: deb=/tmp/libgnome2-vte-perl_0.11-1_amd64.deb
  become: yes

# https://packagecloud.io/asbru-cm/asbru-cm
- copy: src=asbru-cm_5.0.0-1_amd64.deb dest=/tmp/asbru-cm_5.0.0-1_amd64.deb

- name: install asbru-cm
  apt: deb=/tmp/asbru-cm_5.0.0-1_amd64.deb
  become: yes

- name: copy icon
  file: src=server_white.svg dest=/usr/share/icons/hicolor/scalable/apps/server_white.svg
  become: yes

- name: change icon in desktop file
  lineinfile:
    path: /usr/share/applications/asbru-cm.desktop
    regexp: '^Icon=.*'
    line: 'Icon=/usr/share/icons/hicolor/scalable/apps/server_white.svg'
  become: yes

- pause: prompt="Start PAC and close it again."

- file: dest={{ home }}/.config/pac/{{ item }} state=absent
  with_items:
  - pac.dumper
  - pac.nfreeze
  - pac.yml
  - pac.yml.gui
  - pac.yml.tree
  - pac_notray.notified
  - pac_stats.nfreeze


- file: src={{ home }}/Notebooks/carl/.config/pac/{{ item }} dest={{ home }}/.config/pac/{{ item }} state=link
  with_items:
  - pac.dumper
  - pac.nfreeze
  - pac.yml
  - pac.yml.gui
  - pac.yml.tree
  - pac_notray.notified
  - pac_stats.nfreeze


