---
- name: Setup apt repository
  apt_repository:
    repo: "ppa:asbru-cm/{{ asbru_ppa }}"
    state: present
  become: yes


- name: install asbru-cm latest version
  apt:
    name: asbru-cm
    state: latest
  become: yes


- name: copy icon
  copy:
    src: server_white.svg
    dest: /usr/share/icons/hicolor/scalable/apps/server_white.svg
  become: yes


- name: change icon in desktop file
  lineinfile:
    path: /usr/share/applications/asbru-cm.desktop
    regexp: '^Icon=.*'
    line: 'Icon=/usr/share/icons/hicolor/scalable/apps/server_white.svg'
  become: yes


- stat:
    path: '{{ home }}/.config/pac'
  register: pacdir


- pause:
    prompt: "Start PAC and close it again."
  when: not pacdir.stat.exists


- file:
    dest: '{{ home }}/.config/pac/{{ item }}'
    state: absent
  with_items:
    - pac.dumper
    - pac.nfreeze
    - pac.yml
    - pac.yml.gui
    - pac.yml.tree
    - pac_notray.notified
    - pac_stats.nfreeze


- file:
    src: '{{ home }}/Notebooks/carl/.config/pac/{{ item }}'
    dest: '{{ home }}/.config/pac/{{ item }}'
    state: link
  with_items:
    - pac.dumper
    - pac.nfreeze
    - pac.yml
    - pac.yml.gui
    - pac.yml.tree
    - pac_notray.notified
    - pac_stats.nfreeze

