---
- file:
    path: '{{ home }}/apps'
    state: directory

- git:
    repo: https://github.com/larsks/ansible-toolbox.git
    dest: '{{ home }}/apps/ansible-toolbox'

- command: 'python setup.py install'
  args:
    chdir: '{{ home }}/apps/ansible-toolbox'
  become: yes
