---
- apt:
    name:
      - tmux
      - xsel
    state: present
  become: yes

- name: download tmuxrc from git
  git:
    repo: "git@github.com:Charlietje/tmux.git"
    dest: '{{ home }}/tmux'

- name: deploy vim config
  shell: "{{ home }}/tmux/__deploy.sh"

