---
- apt:
    name:
      - tmux
      - xsel
    state: present
  become: yes


- name: create {{ home }}/apps directory
  file:
    path: '{{ home }}/apps'
    state: directory


- name: download tmuxrc from git
  git:
    repo: "https://github.com/OpsCharlie/tmux.git"
    dest: '{{ home }}/apps/tmux'

- name: deploy vim config
  shell: "{{ home }}/apps/tmux/__deploy.sh"

