---
- apt: name=tmux state=present
  become: yes

- name: download tmuxrc from git
  git: repo="https://github.com/Charlietje/tmux.git" dest={{ home }}/tmux

- name: deploy vim config
  shell: "{{ home }}/tmux/__deploy.sh"

- apt: name=xsel state=present
  become: yes
