---
- name: install fail2ban
  apt: name=fail2ban state=present

- name: copy fail2ban http-get-dos.conf
  copy: src=http-get-dos.conf dest=/etc/fail2ban/filter.d/http-get-dos.conf backup=yes

- name: check version fail2ban
  command: dpkg-query -l fail2ban
  register: version
  ignore_errors: yes

- debug: msg={{ version.stdout.find('0.8.6') }}

- name: copy fail2ban sendmail-whois.conf
  copy: src=sendmail-whois.conf dest=/etc/fail2ban/action.d/sendmail-whois.conf backup=yes
  when: version.stdout.find('0.8.6') != -1

- name: copy fail2ban sendmail-whois-lines.conf
  copy: src=sendmail-whois-lines.conf dest=/etc/fail2ban/action.d/sendmail-whois-lines.conf backup=yes
  when: version.stdout.find('0.8.6') != -1

- name: remove defaults-debian.conf
  file: path=/etc/fail2ban/jail.d/defaults-debian.conf state=absent
  when: version.stdout.find('0.8.6') == -1

- name: configure jails
  template: src={{ item }}.j2 dest=/{{ item }} backup=yes
  with_items:
  - etc/fail2ban/jail.local

- name: restart and enable fail2ban
  service: name=fail2ban state=restarted enabled=yes
