---
- apt:
    name:
    - geany
    - geany-plugins
    - geany-plugin-overview
    - gedit-source-code-browser-plugin
    state: latest
  become: yes
  with_items:

- file:
    path: '{{ home }}/.config/geany'
    state: directory

- name: install geany config
  unarchive:
    src: geany.tgz
    dest: '{{ home }}/.config/'

- file:
    path: '{{ home }}/.local/share/gedit'
    state: directory

- unarchive:
    src: gedit.tgz
    dest: '{{ home }}/.local/share/gedit'

- copy:
    src: gedit.conf
    dest: /tmp/gedit.conf

- shell: dconf load /org/gnome/gedit/ < /tmp/gedit.conf
