---
- set_fact:
    installextension: false


- name: install gnome-tweaks
  package:
    name:
      - gnome-tweaks
      - chrome-gnome-shell
    state: present
  become: yes


- name: parse gnome shell version
  shell: gnome-shell --version | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'
  register: r_gnome_extension_parse_shell_version
  changed_when: no


- set_fact:
    gnome_shell_version: "{{ r_gnome_extension_parse_shell_version.stdout }}"


- name: get gnome shell extension info
  uri:
    url: https://extensions.gnome.org/extension-info/?pk={{ item }}&shell_version={{ gnome_shell_version }}
    return_content: yes
  loop: "{{ gnome_extension_ids }}"
  register: r_gnome_extension_info


- include_tasks: install_extension.yml
  vars:
    gnome_extension_info: "{{ item.json }}"
  loop: "{{ r_gnome_extension_info.results }}"
  register: install_extension


- name: reload gnome-shell
  shell: killall -3 gnome-shell
  when: installextension
