---
- apt:
    name:
      - php-cli
      - php-curl
      - php-dom
    state: present
  become: yes

- name: Check if Composer is installed.
  stat:
    path: /usr/local/bin/composer
  register: composer_bin

- name: Download Composer installer.
  get_url:
    url: 'https://getcomposer.org/installer'
    dest: /tmp/composer-installer.php
    mode: '0755'
  when: not composer_bin.stat.exists

- shell: php composer-installer.php
  args:
    chdir: /tmp
  when: not composer_bin.stat.exists

- shell: 'mv /tmp/composer.phar /usr/local/bin/composer'
  when: not composer_bin.stat.exists
  become: yes

- composer:
    global_command: yes
    command: require
    arguments: bramus/mixed-content-scan:~2.8

- file:
    src: "{{ home }}/.config/composer/vendor/bin/mixed-content-scan"
    dest: /usr/local/bin/mixed-content-scan
    state: link
  become: yes



