---
- apt: name=vim state=present
  become: yes
  become_method: sudo

- file: path=/home/carl/.vimrc state=absent
- file: src=/home/carl/Notebooks/carl/.vimrc dest=/home/carl/.vimrc state=link

- file: path=/home/carl/.vim state=absent
- file: src=/home/carl/Notebooks/carl/.vim dest=/home/carl/.vim state=link

- apt: name=vim-gnome state=present
  become: yes
  become_method: sudo

