---
- apt:
    name:
      - vim
      - curl
      - vim-gtk3
      - python3-pip
      - ack
    state: present
  become: yes


- name: create {{ home }}/apps directory
  file:
    path: '{{ home }}/apps'
    state: directory


- name: download vimrc from git
  git:
    repo: "https://github.com/OpsCharlie/vim.git"
    dest: '{{ home }}/apps/vim'


- name: deploy vim config
  shell: "{{ home }}/apps/vim/__deploy.sh"


- name: install pynvim
  pip:
    name: pynvim
