---
- apt:
    name:
      - vim
      - curl
      - vim-gtk3
      - ack
    state: present
  become: yes

- name: download vimrc from git
  git:
    repo: "git@github.com:Charlietje/vim.git"
    dest: '{{ home }}/vim'

- name: deploy vim config
  shell: "{{ home }}/vim/__deploy.sh"


