---
- apt:
    name:
      - vim
      - curl
      - vim-gnome
    state: present
  become: yes

- name: download vimrc from git
  git:
    repo: "https://github.com/Charlietje/vim.git"
    dest: '{{ home }}/vim'

- name: deploy vim config
  shell: "{{ home }}/vim/__deploy.sh"


