---
- name: install aptitude
  apt:
   name: aptitude
   state: present
  become: yes


- name: configure apt-updates
  template:
   src: 'apt-updates.j2'
   dest: '/usr/local/bin/apt-updates'
   mode: '0755'
  become: yes


- name: install cron
  cron:
   name: 'Automatic Updates'
   special_time: reboot
   job: 'sleep 300 && /usr/local/bin/apt-updates'
  become: yes

