---
- apt:
    name: radiotray
    state: latest
  become: yes

- file:
    path: '{{ home }}/.local/share/radiotray'
    state: directory

- copy:
    src: '{{ home }}/Notebooks/carl/.local/share/radiotray/{{ item }}'
    dest: '{{ home }}/.local/share/radiotray/{{ item }}'
  with_items:
  - bookmarks.xml
  - config.xml

