---
- apt: name={{ item }} state=latest
  become: yes
  with_items:
  # - inxi
  - zenmap
  - fwbuilder
  - wireshark
  - etherape
  - speedometer
  - iftop
  - tcpdump
  - iperf
  - nload
  - iptraf
  - nethogs   #bandwidth used by individual processes
  - bmon


