---
- name: Add repositories
  apt_repository: repo="{{item}}"
  become: yes
  become_method: sudo
  ignore_errors: yes
  with_items:
    - "ppa:diodon-team/stable"                       #clipboard manager
    - "ppa:atareao/atareao"                          #my-weather-indicator
    - "ppa:webupd8team/y-ppa-manager"                #y-ppa-manager
    - "ppa:webupd8team/nemo"                         #nemo-filemanager
    - "ppa:nilarimogard/webupd8"                     #gloobus-preview
    - "ppa:linrunner/tlp"                            #power management tool
    - "ppa:ravefinity-project/ppa"                   #themes
    - "ppa:teejee2008/ppa"                           #timeshift
    - "ppa:leolik/leolik"                            #notify-osd
    - "ppa:libreoffice/ppa"                          #libreoffice
    - "ppa:zeal-developers/ppa"                      #zeal


- apt: name={{ item }} state=latest update_cache=yes
  become: yes
  become_method: sudo
  with_items:
  - inxi
  - touchpad-indicator
  - unity-tweak-tool
  - network-manager-openvpn-gnome     #import config from /home/carl/Notebooks/carl/openvpn
  - shutter
  - zeal
  - diodon
  - vagrant
  - nfs-kernel-server
  #- skype
  #- corebird
  - my-weather-indicator
  - y-ppa-manager
  - meld
  - nemo
  - nemo-fileroller
  - nemo-compare
  - nemo-dropbox
  - nemo-media-columns
  - nemo-pastebin
  - nemo-seahorse
  - nemo-share
  - nemo-emblems
  - nemo-image-converter
  - nemo-audio-tab
  - gloobus-preview
  - unoconv
  - gnumeric
  - nemo-gloobus-sushi
  - p7zip
  - unrar
  - zip
  - unzip
  - bleachbit
  - icedtea-8-plugin
  - openjdk-8-jre
  - tlp
  - tlp-rdw
  - vivacious-colors-gtk-dark
  - vivacious-colors-gtk-light
  - timeshift
  - notify-osd
  - notifyosdconfig
  - zenmap
  - fwbuilder
  - vim-gnome
  - wireshark
  - geany
  - geany-plugins
  - compizconfig-settings-manager
  - compiz-plugins-extra
  # - pidgin
  # - pidgin-themes
  # - pidgin-hangouts
  # - pidgin-guifications
  # - pidgin-indicator
  # - pidgin-extprefs
  # - pidgin-plugin-pack
  # - pidgin-libnotify
  # - pidgin-microblog
  # - gstreamer0.10-pulseaudio       # for gtkzabbix

# Nautilus from handling the desktop icons
# and set Nemo as the default file manager
- name: Set nemo as default
  command: "{{ item }}"
  with_items:
  - "gsettings set org.gnome.desktop.background show-desktop-icons false"
  - "xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search"

# revert changes
# - name: Set nautilus as default
  # shell: {{ item }}
  # with_items:
  # - "gsettings set org.gnome.desktop.background show-desktop-icons true"
  # - "xdg-mime default nautilus.desktop inode/directory application/x-gnome-saved-search"

# - name: install window merge plugin
#   copy: src={{ item }} dest=/usr/lib/pidgin/{{ item }}
#   become: yes
#   become_method: sudo
#   with_items:
#   - window_merge.so
#   - window_merge.la

- name: install vagrant bash completion
  become: yes
  become_method: sudo
  get_url: url=https://raw.github.com/kura/vagrant-bash-completion/master/etc/bash_completion.d/vagrant dest=/etc/bash_completion.d/vagrant

- name: create Franz dir
  file: path=/home/carl/Franz state=directory

- name: download franz
  unarchive: src=https://github.com/meetfranz/franz-app/releases/download/4.0.4/Franz-linux-x64-4.0.4.tgz dest=/home/carl/Franz remote_src=yes

- name: set franz icon
  copy: src=/home/carl/Franz/resources/app.asar.unpacked/assets/franz.png dest=/home/carl/.local/share/icons/franz.png remote_src=true

- name: install franz desktop.file
  copy: src=franz.desktop dest=/home/carl/.local/share/applications/franz.desktop

- name: install scripts
  copy: src=/home/carl/Notebooks/scripts/carl_scripts/{{ item }} dest=/usr/local/bin/{{ item }} mode=775 follow=yes
  become: yes
  become_method: sudo
  with_items:
    - convertzim2wiki.sh
    - counter.sh
    - ddig
    - gvim
    - remotecopy.sh
    - sshrm
    - ssl-cert-info
    - swap.sh
    - zabbixevents.sh
    - zabbix_off.wav
    - zabbix_on_average.wav
    - zabbix_on_disaster.wav
    - zabbix_on_high.wav
    - zabbix_on_warning.wav
    - zabbix_on.wav

- name: install startup
  copy: src={{ item }} dest=/home/carl/.config/autostart/{{ item }}
  with_items:
    - radiotray.desktop
    - shutter.desktop
    - remotecopy.sh.desktop
    - zabbixevents.sh.desktop
    - gnome-encfs-manager.desktop

- name: install geany config
  unarchive: src=geany.tgz dest=/home/carl/.config/geany

