---
- apt: name={{ item }} state=latest
  become: yes
  become_method: sudo
  with_items:
  #- touchpad-indicator
  #- unity-tweak-tool
  #- skype
  #- corebird
  - bleachbit
  - geany
  - geany-plugins
  #- compizconfig-settings-manager
  #- compiz-plugins-extra
  - vlc
  - pyrenamer

- file: path=/home/carl/.config/geany state=directory
  become_user: carl

- name: install geany config
  unarchive: src=geany.tgz dest=/home/carl/.config/geany
  become_user: carl
