---
- apt: name={{ item }} state=latest
  become: yes
  with_items:
  #- touchpad-indicator
  #- unity-tweak-tool
  #- skype
  #- corebird
  - bleachbit
  - geany
  - geany-plugins
  #- compizconfig-settings-manager
  #- compiz-plugins-extra
  - vlc
  - pyrenamer

- file: path={{ home }}/.config/geany state=directory

- name: install geany config
  unarchive: src=geany.tgz dest={{ home }}/.config/geany
