---
- name: Add repositories
  apt_repository: repo="{{item}}"
  become: yes
  become_method: sudo
  ignore_errors: yes
  with_items:
    - "ppa:diodon-team/stable"
    - "ppa:atareao/atareao"
    - "ppa:webupd8team/y-ppa-manager"
    - "ppa:webupd8team/nemo"
    - "ppa:nilarimogard/webupd8"
    - "ppa:linrunner/tlp"
    - "ppa:ravefinity-project/ppa"


- apt: name={{ item }} state=latest
  become: yes
  become_method: sudo
  with_items:
  - inxi
  - network-manager-openvpn-gnome     #import config from /home/carl/Notebooks/carl/openvpn
  - shutter
  - zeal
  - diodon
  - vagrant
  - nfs-kernel-server 
  - skype 
  - corebird
  - my-weather-indicator
  - y-ppa-manager
  - meld
  - nemo
  - nemo-fileroller
  - nemo-compare
  - nemo-dropbox
  - nemo-media-columns
  - nemo-pastebin
  - nemo-seahorse
  - nemo-share
  - nemo-emblems
  - nemo-image-converter
  - nemo-audio-tab
  - gloobus-preview
  - unoconv
  - gnumeric
  - nemo-gloobus-sushi
  - p7zip
  - unrar
  - zip
  - unzip
  - bleachbit
  - icedtea-8-plugin 
  - openjdk-8-jre
  - tlp
  - tlp-rdw
  - vivacious-colors-gtk-dark
  - vivacious-colors-gtk-light


# Nautilus from handling the desktop icons
# and set Nemo as the default file manager
- name: Set nemo as default
  command: "{{ item }}"
  with_items:
  - "gsettings set org.gnome.desktop.background show-desktop-icons false"
  - "xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search"

# revert changes
# - name: Set nautilus as default
  # shell: {{ item }}
  # with_items:
  # - "gsettings set org.gnome.desktop.background show-desktop-icons true"
  # - "xdg-mime default nautilus.desktop inode/directory application/x-gnome-saved-search"

